spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@webfluxcoursecluster.rzfjaow.mongodb.net/${DB_NAME}?retryWrites=true&w=majority&appName=WebfluxCourseCluster
  application:
    name: webflux-course-reactive
